name: chaleride
description: carpooling service
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  connectivity_plus: ^5.0.2
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  hive: ^2.2.3
  logger: ^2.5.0
  sizer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/

  
  fonts:
    - family: 'Montserrat'
      fonts:
        - asset: assets/font/montserrat/Montserrat-Light.ttf
          weight: 200
        - asset: assets/font/montserrat/Montserrat-Medium.ttf
          weight: 400
        - asset: assets/font/montserrat/Montserrat-SemiBold.ttf
          weight: 500
        - asset: assets/font/montserrat/Montserrat-Bold.ttf
          weight: 700